build mvn and nodeapp

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -124,3 +124,69 @@ jobs:
           docker push $BACKEND_IMAGE:${{ github.sha }}
           docker push $FRONTEND_IMAGE:${{ github.sha }}
 
+  dast-test:
+    runs-on: ubuntu-latest
+    needs: run-container
+
+    steps:
+
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      # Build containers
+      - name: Build containers
+        run: docker compose build
+
+      # Start services
+      - name: Start application stack
+        run: docker compose up -d
+
+      # Wait until backend is ready
+      - name: Wait for backend
+        run: |
+          for i in {1..30}; do
+            if curl -s http://localhost:8080 > /dev/null; then
+              echo "Backend ready"
+              exit 0
+            fi
+            echo "Waiting for backend..."
+            sleep 5
+          done
+          echo "Backend failed to start"
+          docker compose logs backend
+          exit 1
+
+      # -----------------------------
+      # OWASP ZAP DAST Scan
+      # -----------------------------
+
+      - name: Run OWASP ZAP Baseline Scan
+        run: |
+          docker run --network="host" \
+          -v $(pwd):/zap/wrk/:rw \
+          ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
+          -t http://localhost:8080 \
+          -J zap-report.json \
+          -r zap-report.html
+
+      # -----------------------------
+      # Check for Critical Vulnerabilities
+      # -----------------------------
+
+      - name: Fail pipeline if CRITICAL vulnerabilities found
+        run: |
+          if grep -i "High" zap-report.json; then
+            echo "CRITICAL/HIGH vulnerabilities found!"
+            exit 1
+          else
+            echo "No critical vulnerabilities found"
+          fi
+
+      # Upload report artifact
+      - name: Upload ZAP Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: zap-dast-report
+          path: |
+            zap-report.html
+            zap-report.json
